# Generated by Django 6.0.2 on 2026-02-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_grasss_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
