# Generated by Django 6.0.2 on 2026-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_studentprofile_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='diagnostic_questions_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
